services:
  - type: web
    name: telegram-channel-repost-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHANNEL
        sync: false
      - key: ADMINS
        sync: false
